apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault
  namespace: istio-system
spec:
  vault:
    server: http://vault.example.com:8200
    path: pki_int_east/sign/cluster-east-issuer
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token
